name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt (6.x)
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.3
          host: linux
          target: desktop
          arch: gcc_64
          cache: true

      - name: Configure (CMake)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests (ctest)
        run: ctest --test-dir build --output-on-failure

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            build/**
            !build/CMakeFiles/**
            !build/**/CMakeFiles/**
