name: CI
on:
  push: { branches: [main, master] }
  pull_request: { branches: [main, master] }
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt via apt
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qt6-base-dev qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools \
            qml6-module-qtquick qml6-module-qtqml qml6-module-qtquick-controls \
            qml6-module-qttest qml6-module-qtqml-workerscript \
            libxkbcommon-dev libgl1-mesa-dev libx11-dev libxext-dev \
            libvulkan-dev

      - name: Configure
        run: cmake -S CI_CD_Test -B CI_CD_Test/build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build CI_CD_Test/build --parallel

      - name: Test (headless)
        env:
          QT_QPA_PLATFORM: offscreen
        run: ctest --test-dir CI_CD_Test/build --output-on-failure

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: CI_CD_Test/build/**
