name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.3
          host: linux
          target: desktop
          arch: gcc_64
          cache: true

      - name: Configure
        run: cmake -S CI_CD_Test -B CI_CD_Test/build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build CI_CD_Test/build --parallel

      - name: Test
        env:
          QT_QPA_PLATFORM: offscreen
        run: ctest --test-dir CI_CD_Test/build --output-on-failure

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: CI_CD_Test/build/**
