# .github/workflows/release.yml
name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.3
          host: linux
          target: desktop
          arch: gcc_64
      - name: Configure (Release)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --parallel
      - name: Package (tar.gz)
        run: |
          cd build
          tar -czf app-linux-x64.tar.gz *
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app-linux-x64.tar.gz
