name: Release
on:
  push:
    tags:
      - 'v*'          # tags like v0.1.0, v1.2, etc.
  workflow_dispatch: {}  # allow manual runs too

permissions:
  contents: write        # needed to create a GitHub release

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensure tags are available in the workspace

      - name: Install Qt via apt
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qt6-base-dev qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools \
            qml6-module-qtquick qml6-module-qtquick-window qml6-module-qtquick-controls \
            qml6-module-qtquick-layouts qml6-module-qtqml qml6-module-qttest \
            qml6-module-qtqml-workerscript \
            libxkbcommon-dev libgl1-mesa-dev libx11-dev libxext-dev libvulkan-dev

      - name: Configure (Release)
        run: cmake -S CI_CD_Test -B CI_CD_Test/build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build CI_CD_Test/build --parallel

      - name: Package
        run: |
          cd CI_CD_Test/build
          tar -czf HeadUnitApp-linux-x64.tar.gz HeadUnitApp

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: CI_CD_Test/build/HeadUnitApp-linux-x64.tar.gz
          generate_release_notes: true
